### ISSUE TITLE
Remove "Add to LMS" functionality

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#10]
Ayamel was originally designed to work with a variety of LMS's, and Ayamel World will continue to support this. 

But the BYU instance of Ayamel doesn't need this functionality. Everything we need will come from AIM.

However, in the far flung future, we may want Ayamel to send student data (Time watched, number of words clicked on) directly to Learning Suite as a form of auto-grading. 

Should we leave this functionality in, (as in comment it out for now). Or just delete it all?

**Comment by verdude** [comment]
Made some destructive changes to the database to remove lmskey's from the course table. As a result, all site-permissions are wiped when the commit is applied: 76b490609b91d423dd7fe5654f9a2daa45eb7e3e
