### ISSUE TITLE
Automatically enter students into courses based on CAS login by accessing AIM

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#20]
When a user logs in via CAS, we can take their credentials and check which courses they are enrolled in this semester through AIM.

Upon obtaining the list of courses the student is in, enroll them in Ayamel courses that have the exact same name. (Relies on functionality in Issue #1).

If this is not a computationally expensive task, go ahead and run this check every time a user logs in. 

If a student drops a course (the course isn't listed in AIM), remove them from the course.

**Comment by verdude** [comment]
Needs to be tested.

Users courses are updated on ayamel every time they log in. Not really implemented for teachers yet.
