### ISSUE TITLE
Automatically set permissions based on CAS credentials through AIM.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#21]
When a user logs in via CAS, access their credentials through AIM and check if they're a Teacher or a Student.

If they are a Teacher, make sure they have teacher permissions.

If they are a Student, make sure they only have student permissions.

If they are a TA or an administrator, DO NOT remove those permissions.

**Comment by verdude** [comment]
8ffa46b67512c1c0ceeb099a77bd2978234fe851
