### ISSUE TITLE
Update CSS to Twitter Bootstrap 3.3.7

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#23]
Ayamel currently runs using CSS from Twitter Bootstrap 2.3.0. When streamlining Ayamel we should try installing Twitter Bootstrap 3.3.7 and see the UI changes. This should give Ayamel a more modern look.

http://getbootstrap.com/

**Comment by bradenhutch** [comment]
Finished (for the most part) and pushed to the beta site. Will continue to fix bootstrap related issues as they come up.
