### ISSUE TITLE
Link notifications to a corresponding page

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/Ayamel#35]
Currently, notifications can be accessed when a notification number icon appears next to ones profile picture. In the notification window, a new notification can marked as read with a single click and erased by clicking on them again. It would be useful if clicking on a notification could link you to a page relating to it.

For example, clicking on a notification about a student requesting to join a course should link to the "student requests" on the corresponding course. Clicking on a notification for a student being added to a course should link to that course. 

Here is an example of what the new notifications menu might look like. It could also just be a little module that pops up when you click the notification number that shows up next to the profile picture (similar to in Facebook etc.) 

![notifications](https://cloud.githubusercontent.com/assets/22623998/22320872/42c3a1ee-e34d-11e6-8abb-fed8cf6a86a3.JPG)

**Comment by JKJensen** [comment]
Is this for Y-Video? If so, we really don't need notifications at all. Messaging functionality already exists in Learning Suite. And if Admins need to contact professors, we can just email them because we know their NetID (CAS).

And for the case above, we don't have closed/open courses in Y-Video. Just have students login and have them auto-enroll in the course.

**Comment by bradenhutch** [comment]
It's not so much for messaging as it is for students being added to courses for special reasons.

For example, you could have a student/professor who wants to observe the content for a course on ayamel that they are not officially enrolled. In a case like this, they would need to request to join the course. If they request to join a course, then the instructor would receive a notification as to whether they will let them join the course or not. When that user is accepted into the course, they could receive a notification as well. 

Also, there are courses (for example, the Russian department is currently working on a catch-all course of content for all of their classes) that couldn't be auto-enrolled through CAS either. There are also cases where graduate students have been using ayamel to conduct research which would give them a need to create their own courses that are off the grid of BYU.

**Comment by bradenhutch** [comment]
These will no longer be needed after the upgrade to Y-Video. Student's will no longer be able to request access to courses/elevated permissions. These will all have to be granted from the teacher's collection settings.
