### ISSUE TITLE
Add TA via netID

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#4]
In a course, under the "Course Members" box, a button should appear near the top called: "Add TA."

A dialogue box should show up that contains the following

> Input Teacher's Assistant netID:
> [Input Box]
> [Submit]

Now that the netID has been stored. That TA now has access to the course and full editing permissions. The only thing a TA can't do in a course is delete other TA's.

Professor's that have created the course will be able to delete previous TA's.

The input box can accept multiple names separated by a comma.

**Comment by verdude** [comment]
d3ad2b63bfc36de485e134884df828e5398fbbd4
