### ISSUE TITLE
Can't save 2 subtitle tracks at a time

### ISSUE THREAD

**Issue by verdude** [BYU-ODH/Ayamel#54]
When changes have been made to more than one track, neither track can be saved at all - even if you select the save button and select both tracks. Saving one track is possible even if multiple tracks are open as long as it is the only one with changes.

**Comment by bradenhutch** [comment]
This seems to be related to #49. Also, subtitle tracks cannot be saved over. Saving a new track still works though.

**Comment by bradenhutch** [comment]
I'm unable to recreate any errors in saving multiple tracks. This should be clear.
