### ISSUE TITLE
Simplify course permissions

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/Ayamel#56]
This will probably go hand in hand with #33.

Currently, students in a course can be given a wide variety of privileges as shown below.
![image](https://cloud.githubusercontent.com/assets/22623998/26258549/5552a722-3c82-11e7-847d-d683770c78de.png)

However, many of these privileges will become unnecessary due to other upgrades (ie getting rid of course announcements). Also, others will become obsolete due to AIM integration (or will only be used in special cases ie a teacher who is doing research or wants to share their course with a student not enrolled in a course). It would be simpler if the only options were as follows:

-Course Admin (aka TA)
-Add/Remove TAs (since it might not be wise to give TAs this privilege)
-Add/Remove Teachers (ditto the above)

Currently, an "Add TA" button has been added which automatically enrolls a student in a course if they aren't enrolled already and gives them course admin privileges (?). It might be wise to add an "add/remove teacher" button as well to anticipate one teacher taking over for another teacher's course or multiple teachers teaching one course. There is currently no option to add teachers despite their being an "Add Teachers to Course" permission available.

It should also be noted that in Y-Video, all usernames will be replaced by NetIDs (except maybe in the case of admins... they could have a default netID of ADMIN or something like that). Therefore, the "Username" column should be updated to "NetID."
![image](https://cloud.githubusercontent.com/assets/22623998/26259036/737f6d14-3c84-11e7-8d66-54dcc2aa9d19.png)
 
Also, teachers are not displayed in this menu either. Teachers should be displayed as well.

**Comment by dro248** [comment]
02e670f2d7c660015061ca69e98de5490d3061b4
