### ISSUE TITLE
Issues with the collapsible navbar when viewing content

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/Ayamel#58]
The navbar on the content view page is meant to condense when the browser gets horizontally smaller. This is a feature of bootstrap 3 that will make the site easier to navigate on mobile browsers and the like. A button can then be pressed that expands the navbar so that the buttons etc. are visible.

Currently, the navbar condenses correctly when the browser gets smaller, but when the button to expand it is pressed, the content displays for a split second and then disappears. A thin line can be seen where the content should have expanded and then disappears when the button is pressed again. Also, inspecting the source of the page shows that the content did expand, but it is behind the video.

**Comment by dro248** [comment]
The issue appears to have been a conflict between 2 Bootstrap files in Ayamel/app/views/content/header/main.scala.html.
