### ISSUE TITLE
Students: Top bar

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#6]
Right now on Ayamel the top bar for students contains the following:
<img width="1175" alt="screenshot 2016-09-23 12 05 38" src="https://cloud.githubusercontent.com/assets/5481718/18796395/4d3b98f8-8186-11e6-919d-628f3dd6933e.png">

The student view should give them the following top bar:
![studenttopbar](https://cloud.githubusercontent.com/assets/5481718/18847600/165bb00c-83e8-11e6-8880-a2e7b55dd688.png)

Students lose access to My Content. The Home Page is accessed via clicking on the "Ayamel" Logo.

The courses they are in are listed alphabetically on top, and IF there are extra courses that are not viewable, they should be listed under "Other courses."

**Comment by trevren11** [comment]
Closing without doing. Unnecessary
