### ISSUE TITLE
Students: Remove Configuration Bar

### ISSUE THREAD

**Issue by JKJensen** [BYU-ODH/Ayamel#8]
The configuration bar that is crucial for Professors and TA's should be removed entirely for Students.

Before:
<img width="1186" alt="screenshot 2016-09-23 12 20 52" src="https://cloud.githubusercontent.com/assets/5481718/18796861/6834216e-8188-11e6-9a85-925038de5de0.png">

After:
![studentcontentview](https://cloud.githubusercontent.com/assets/5481718/18797026/1babed26-8189-11e6-9cf9-99d8a2d9476d.png)

This removes the share, clone, and caption/annotation editing from normal students.

**Comment by trevren11** [comment]
Should this issue be closed then @gliese1337?

**Comment by gliese1337** [comment]
Not necessarily. You may well want to remove those other options, and put access to CaptionAider somewhere else.

**Comment by verdude** [comment]
Solved by removing students' permissions to create content (b3e8105a99f8d30853ad30ede31b4aa5a6650ad0). Now they only see the text option in the bar. There is a new issue addressing the share option.
